Repository yoshitokamizato/go-to-nago, pull requests merged in 2020-07, with the labels that each got.

#80 Bug/path
  app/assets/images/no-image.png
  app/assets/stylesheets/users/show.scss
  app/views/publics/_before_login_header.html.erb
  app/views/users/show.html.erb
Labels: bug

#81 seeds.rbの不要なファイルを削除
  db/seeds.rb
Labels: enhancement

#83 Bug/edit view sort
  ,
  app/views/facilities/bookmark.html.erb
  app/views/users/show.html.erb
Labels: bug

#85 fix facility-name sort
  app/views/facilities/bookmark.html.erb
  app/views/publics/_before_login_header.html.erb
  app/views/publics/_header.html.erb
Labels: bug

#101 Feature/add profile edit
  app/controllers/application_controller.rb
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/controllers/users/passwords_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/users/sessions_controller.rb
  app/controllers/users/unlocks_controller.rb
  app/views/devise/registrations/edit.html.erb
  app/views/publics/_before_login_header.html.erb
  app/views/publics/_header.html.erb
  app/views/users/show.html.erb
  config/routes.rb
  public/uploads/user/image/1/猫.png
Labels: feature

#103 Update/databese yml
  config/database.yml
Labels: enhancement

#102 退会処理を実装
  .gitignore
  app/assets/stylesheets/application.scss
  app/controllers/users_controller.rb
  app/views/users/confirm.html.erb
  app/views/users/show.html.erb
  app/views/users/withdraw.html.erb
  config/routes.rb
  public/uploads/user/image/1/猫.png
  public/uploads/user/image/3/coffee.png
Labels: feature

#131 Add edit password page
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/main/fixedpages.scss
  app/controllers/application_controller.rb
  app/controllers/fixedpages_controller.rb
  app/controllers/users/registrations_controller.rb
  app/views/devise/registrations/edit_password.html.erb
  app/views/fixedpages/privacy.html.erb
  app/views/fixedpages/tos.html.erb
  app/views/publics/_footer.html.erb
  app/views/users/show.html.erb
  config/routes.rb
Labels: feature

#144 Feature/email edit page
  app/controllers/application_controller.rb
  app/controllers/users/confirmations_controller.rb
  app/controllers/users/registrations_controller.rb
  app/mailers/users/mailer.rb
  app/models/user.rb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/edit_email.html.erb
  app/views/devise/registrations/update_email_confirm.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/users/show.html.erb
  config/environments/development.rb
  config/initializers/devise.rb
  config/locales/devise.views.ja.yml
  config/routes.rb
  db/migrate/20200724072527_add_confirmation_to_users.rb
  db/schema.rb
Labels: feature

#155 ボトムエリア(ソーシャルボタン、情報掲載依頼ボタン）のテンプレート化
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/main/facilities.scss
  app/views/facilities/bookmark.html.erb
  app/views/facilities/index.html.erb
  app/views/facilities/show.html.erb
  app/views/facilities/show_facility.html.erb
  app/views/facilities/show_gourmet.html.erb
  app/views/menus/index.html.erb
  app/views/publics/_bottom_area.html.erb
  app/views/users/show.html.erb
Labels: enhancement
